Player-mgt-system/Models/Trophy.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Player_mgt_system.Models
{
    public class Trophy
    {
        [Key]
        public int TrophyId { get; set; }
        [Column(TypeName="nvarchar(250)")]
        [DisplayName("Trophy Name")]
        [Required]
        public string TrophyName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string Venue { get; set; }
        
        public List<TrophyMatch> TrophyMatchList { get; set; }
        
        
        public List<Player_Trophy> Player_Trophies { get; set; }
        
        public List<Trophy_Team> Trophy_Team { get; set; }
    }
}

Player-mgt-system/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.Models;

namespace Player_mgt_system.Controllers
{
    public class TeamController : Controller
    {
        private readonly PlayerContext _context;

        public TeamController(PlayerContext context)
        {
            _context = context;
        }

        // GET: Team
        public async Task<IActionResult> Index()
        {
            if(!string.IsNullOrWhiteSpace(HttpContext.Session.GetString(SessionVariables.SessionKeyUsername))){
                return _context.Team != null ? 
                    View(await _context.Team.ToListAsync()) :
                    Problem("Entity set 'PlayerContext.Team'  is null.");       
            }

            return RedirectToAction("Index", "Login");
        }

        // GET: Team/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Team/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Team/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamId,TeamName,TeamOwner,TeamState,Description,MaxPrice")] Team team)
        {
                var owner = await _context.Owner
                .FirstOrDefaultAsync(m => m.OwnerId == Int32.Parse(team.TeamOwner));
                team.TeamOwner = owner.OwnerName;
                _context.Add(team);
                await _context.SaveChangesAsync();
                return View();
            
        }

        // GET: Team/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Team/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeamId,TeamName,TeamOwner,TeamState,Description,MaxPrice")] Team team)
        {
            if (id != team.TeamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.TeamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Team/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Team == null)
            {
                return Problem("Entity set 'PlayerContext.Team'  is null.");
            }
            var team = await _context.Team.FindAsync(id);
            if (team != null)
            {
                _context.Team.Remove(team);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
          return (_context.Team?.Any(e => e.TeamId == id)).GetValueOrDefault();
        }
        
        public async Task<IActionResult> AddPlayers(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return null;
        }
        public IActionResult GetTeams()
        {
            var teams =
                _context.Team.Select(r=>r).ToList();

            return Ok(teams);
        }
    }
}

Player-mgt-system/Controllers/TrophyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.dto;
using Player_mgt_system.Models;

namespace Player_mgt_system.Controllers
{
    public class TrophyController : Controller
    {
        private readonly PlayerContext _context;

        public TrophyController(PlayerContext context)
        {
            _context = context;
        }

        // GET: Trophy
        public async Task<IActionResult> Index()
        {
              return _context.Trophy != null ? 
                          View(await _context.Trophy.ToListAsync()) :
                          Problem("Entity set 'PlayerContext.Trophy'  is null.");
        }

        // GET: Trophy/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trophy == null)
            {
                return NotFound();
            }

            var trophy = await _context.Trophy
                .FirstOrDefaultAsync(m => m.TrophyId == id);
            
            if (trophy == null)
            {
                return NotFound();
            }

            var lisr = await _context.TrophyMatch.ToListAsync();


            var trophyMatch = lisr.Where(obj => obj.Trophy.Equals(trophy)).ToList();

            trophy.TrophyMatchList = trophyMatch;
            
            return View(trophy);
        }

        // GET: Trophy/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trophy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrophyId,TrophyName,StartDate,EndDate,Venue")] Trophy trophy)
        {
            if (ModelState.IsValid)
            {
                _context.Add(trophy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trophy);
        }

        // GET: Trophy/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trophy == null)
            {
                return NotFound();
            }

            var trophy = await _context.Trophy.FindAsync(id);
            if (trophy == null)
            {
                return NotFound();
            }
            return View(trophy);
        }

        // POST: Trophy/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TrophyId,TrophyName,StartDate,EndDate,Venue")] Trophy trophy)
        {
            if (id != trophy.TrophyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trophy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrophyExists(trophy.TrophyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trophy);
        }

        // GET: Trophy/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trophy == null)
            {
                return NotFound();
            }

            var trophy = await _context.Trophy
                .FirstOrDefaultAsync(m => m.TrophyId == id);
            if (trophy == null)
            {
                return NotFound();
            }

            return View(trophy);
        }

        // POST: Trophy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trophy == null)
            {
                return Problem("Entity set 'PlayerContext.Trophy'  is null.");
            }
            var trophy = await _context.Trophy.FindAsync(id);
            if (trophy != null)
            {
                _context.Trophy.Remove(trophy);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrophyExists(int id)
        {
          return (_context.Trophy?.Any(e => e.TrophyId == id)).GetValueOrDefault();
        }
        [HttpPost]
        public async Task<IActionResult> CreateTrophy(TrophyDto dto)
        {
            //open transactrion
            var transaction = _context.Database.BeginTransaction();
            
            try
            {
                var Trophy = new Trophy();

                Trophy.Venue = dto.Venue;
                Trophy.StartDate = dto.StartDate;
                Trophy.EndDate = dto.EndDate;
                Trophy.TrophyName = dto.TrophyName;

                _context.Add(Trophy);

                await _context.SaveChangesAsync();


                foreach (var TrophyMatchData in dto.TrophyMatchList)
                {
                    var TrophyMatch = new TrophyMatch();
                    TrophyMatch.Date = TrophyMatchData.Date;
                    TrophyMatch.Location = TrophyMatchData.Location;
                    TrophyMatch.MatchName = TrophyMatchData.MatchName;
                    TrophyMatch.Trophy = Trophy;
                    _context.Add(TrophyMatch);
                }
                foreach (var teamId in dto.ParticipatingTeams)
                {
                    var TrophyTeam = new Trophy_Team();
                    
                    TrophyTeam.TeamId = Int32.Parse(teamId);
                    TrophyTeam.TrophyId = Trophy.TrophyId;
                    
                    var Team =  _context.Team.Find(Int32.Parse(teamId));
                    
                    TrophyTeam.Trophy = Trophy;
                    TrophyTeam.Team = Team;
                    
                    _context.Add(TrophyTeam);
                }
                await _context.SaveChangesAsync();
                
                //all changes occored successfully
                transaction.Commit();
                
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                //rolled back
                transaction.Rollback();
                throw;
            }
        }
    }
}

Player-mgt-system/Views/Trophy/Create.cshtml
@model Player_mgt_system.Models.Trophy

@{
    ViewData["Title"] = "Create";
}


<div class="card">
  <div class="card-header">
    Create New Trophy
  </div>
  <div class="card-body">
      <form  id="trophyForm">
          <div asp-validation-summary="ModelOnly" class="text-danger"></div>
          <div class="row">
              <div class="form-group col-md-6">
                  <label asp-for="TrophyName" class="control-label"></label>
                  <input asp-for="TrophyName" id="TrophyName" class="form-control" />
                  <span asp-validation-for="TrophyName" class="text-danger"></span>
              </div>
              <div class="form-group col-md-6">
                  <label asp-for="StartDate" class="control-label"></label>
                  <input asp-for="StartDate" id="StartDate" class="form-control" />
                  <span asp-validation-for="StartDate" class="text-danger"></span>
              </div>
              <div class="form-group col-md-6">
                  <label asp-for="EndDate" class="control-label"></label>
                  <input asp-for="EndDate" id="EndDate" class="form-control" />
                  <span asp-validation-for="EndDate" class="text-danger"></span>
              </div>
              <div class="form-group col-md-6">
                  <label asp-for="Venue" class="control-label"></label>
                  <input asp-for="Venue" id="Venue" class="form-control" />
                  <span asp-validation-for="Venue" class="text-danger"></span>
              </div>
              <div class="form-group col-md-6">
                  <label  class="control-label">Participating Teams</label>
                  <select  class="form-select" aria-label="Default select example" id="participatingTeams" multiple>
                  </select>
              </div>
             
          </div>
      </form>
      <hr/>
      <!--Match detail section-->
      <div class="card">
          <div class="card-header">
            Match Details
          </div>
          <div class="card-body">
              
              <div class="row">
                  <div class="form-group col-md-6">
                      <label  class="control-label">Match Name</label>
                      <input id="matchName" type="text" class="form-control" />
                  </div>
                  <div class="form-group col-md-6">
                      <label  class="control-label">Date</label>
                      <input  id="matchDate" type="date" class="form-control" />
                  </div>
                  <div class="form-group col-md-6">
                      <label  class="control-label">Location</label>
                      <input id="location" type="text" class="form-control" />
                  </div>
                  <div class="form-group col-md-3">
                      <i class="fa-solid fa-plus mt-5" onclick="setMacthDetail()" style="cursor: pointer"></i>
                  </div>
                  
                  <div class="form-group col-md-12 mt-2">
                      <table class="table">
                          <thead>
                          <tr>
                              <th>Match Name</th>
                              <th>Date Time</th>
                              <th>Location</th>
                          </tr>
                          </thead>
                          <tbody id="matchTableBody">
                            
                          </tbody>
                      </table>
                  </div>
                  
              </div>
              
          </div>
      </div>
      <div class="form-group col-md-12 align-content-end">
          <input type="button" onclick="submitData()" value="Create" class="btn btn-success mt-2" />
      </div>
      
</div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    let matchDetailList=[];
    let participatingTeams=[];
    getTeams();
    $('#participatingTeams').change(function() {
        participatingTeams.length!==0?participatingTeams.length=0:'';
        participatingTeams=$(this).val();
    });
    function setMacthDetail() {
 
        let matchName = $("#matchName").val();
        let matchDate= $("#matchDate").val();
        let location=$("#location").val();
        
        let matchDetail={
            MatchName:matchName,
            Date:matchDate,
            Location:location
            
        }
        matchDetailList.push(matchDetail);
        
        $("#matchTableBody").append("<tr><td>" + matchName + 
                                             "</td><td>" + matchDate + "</td><td>"+location+"</td></tr>");
        
        
        
    }
    
    function submitData(){     
            let trophyData={
                TrophyName:$("#TrophyName").val(),
                StartDate:$("#StartDate").val(),
                EndDate:$("#EndDate").val(),
                Venue:$("#Venue").val(),
                TrophyMatchList:matchDetailList,
                ParticipatingTeams:participatingTeams
            }
           $.ajax({
                type: 'POST',
                url:  '@Url.Action("CreateTrophy", "Trophy")',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                data: trophyData ,
                success: function (result) {
                    alert('Successfully Created');
                    location.reload()
                },
                error: function () {
                    alert('Failed to create trophy');
                }
           })
                                   
    }
    
         function getTeams(){
                 $.ajax({
                    type: 'GET',
                    url:  '@Url.Action("GetTeams", "Team")',
                    success: function (result) {
                        $.each(result, function (key, entry) {
                            $("#participatingTeams").append($('<option></option>').
                            attr('value', entry.teamId).text(entry.teamName));
                          })
                    },
                    error: function () {
                        console.log('Failed ');
                    }
                 });
                 
                 
            }
</script>

Player-mgt-system/Views/Trophy/Delete.cshtml
@model Player_mgt_system.Models.Trophy

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trophy</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TrophyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TrophyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-route-id="@Model.TrophyId">
        <input type="hidden" asp-for="TrophyId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Player-mgt-system/Views/Trophy/Details.cshtml
@model Player_mgt_system.Models.Trophy

@{
    ViewData["Title"] = "Details";
}

<div class="card">
    <div class="card-header">
        Trophy Details
    </div>
    <div class="card-body">
        <div>
   
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.TrophyName)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.TrophyName)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.StartDate)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.StartDate)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.EndDate)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.EndDate)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Venue)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Venue)
                </dd>
            </dl>
            <hr/>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Match Name
                        </th>
                        <th>
                           Date Time
                        </th>
                        <th>
                           Location
                        </th>
                    </tr>
                </thead>
                <tbody>
            @foreach (var item in Model.TrophyMatchList) {
                <tr>
                    <td>
                         @item.MatchName  
                    </td>
                    <td>
                        @item.Date
                    </td>
                    <td>
                        @item.Location
                    </td>

                </tr>
            }
                </tbody>
            </table>
</div>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TrophyId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Player-mgt-system/Views/Trophy/Edit.cshtml
@model Player_mgt_system.Models.Trophy

@{
    ViewData["Title"] = "Edit";
}
<div class="card">
  <div class="card-header">
    Edit Trophy Details
  </div>
  <div class="card-body">
        <form asp-action="Edit" asp-route-id="@Model.TrophyId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TrophyId" />
            <div class="row">

            <div class="form-group col-md-6">
                <label asp-for="TrophyName" class="control-label"></label>
                <input asp-for="TrophyName" class="form-control" />
                <span asp-validation-for="TrophyName" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6 mt-2">
                <input type="submit" value="Edit" class="btn btn-success" />
            </div>
            </div>

        </form>
    
  </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Player-mgt-system/Views/Trophy/Index.cshtml
@model IEnumerable<Player_mgt_system.Models.Trophy>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="Create" style="color: green"><i class="fa-solid fa-file-circle-plus"></i> Create New Trophy</a>
</p>
<div class="card">
  <div class="card-header">
    Team Details
  </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.TrophyName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StartDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EndDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Venue)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrophyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Venue)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.TrophyId" style="color: green"> <i class="fa-regular fa-pen-to-square"></i> Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.TrophyId"> <i class="fa-regular fa-eye"></i> View</a> |
                        <a asp-action="Delete" asp-route-id="@item.TrophyId" style="color: red"><i class="fa-regular fa-trash"></i> Delete</a>
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>