Player-mgt-system/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Player_mgt_system.Models;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.dto;

namespace Player_mgt_system.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PlayerContext _context;
        public DashboardController(ILogger<HomeController> logger,PlayerContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            if(!string.IsNullOrWhiteSpace(HttpContext.Session.GetString(SessionVariables.SessionKeyUsername))){
                return View();       
            }

            return RedirectToAction("Index", "Login");
        }
        
        public IActionResult    GetUserData()
        {
            HttpContext.Session.GetString("SessionVariables.SessionKeyUsername");
            var user =
                _context.Users.Where(obj => obj.Username.Equals(HttpContext.Session.GetString(SessionVariables.SessionKeyUsername)));

            return Ok(user);
        }
        public IActionResult  GetDashboardData()
        {
            var teamCount = _context.Team.Count();
            var playerCount = _context.players.Count();
            var tropyCount = _context.Trophy.Count();
            var teamOwnersCount = _context.Owner.Count();

            DashboardDto dto = new DashboardDto();
            dto.TeamCount = teamCount;
            dto.PlayerCount = playerCount;
            dto.TrophyCount = tropyCount;
            dto.OwnerCount = teamOwnersCount;
            return Ok(dto);
        }
    }
    
}

Player-mgt-system/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.dto;
using Player_mgt_system.Models;

namespace Player_mgt_system.Controllers
{
    public class PlayerController : Controller
    {
        private readonly PlayerContext _context;

        public PlayerController(PlayerContext context)
        {
            _context = context;
        }

        // GET: Player
        public async Task<IActionResult> Index()
        {
            //if(!string.IsNullOrWhiteSpace(HttpContext.Session.GetString(SessionVariables.SessionKeyUsername))){
                return View(await _context.players.ToListAsync());       
            //}

            return RedirectToAction("Index", "Login");
        }

        // GET: Player/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.players == null)
            {
                return NotFound();
            }

            var player = await _context.players
                .FirstOrDefaultAsync(m => m.PlayId == id);
            if (player == null)
            {
                return NotFound();
            }
            
            
            return View(player);
        }

        // GET: Player/Create
        public IActionResult Create()
        {
            //if(!string.IsNullOrWhiteSpace(HttpContext.Session.GetString(SessionVariables.SessionKeyUsername))){
                return View();       
           // }

            return RedirectToAction("Index", "Login");
            
        }

        // POST: Player/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserDto userDto)
        {
            //validate user
            bool isExist = _context.Users.Any(e => e.Username.Equals(userDto.UserName));

            if (isExist) {
                return NotFound("User Already Exist");
            }

            var user = new User();

            
            user.Username = userDto.UserName;
            user.Password = BCrypt.Net.BCrypt.HashPassword(userDto.Password);
            user.role = "USER_PLAYER";
            user.AuthStatus= "NOT_AUTHORIZED";

            _context.Add(user);

            await _context.SaveChangesAsync();


            //create player
            var player = new Player();
            player.PlayerName = userDto.PlayerName;
            player.Description= userDto.Description;
            player.Speciality= userDto.Speciality;
            player.BasePrice= userDto.BasePrice;
            player.Country= userDto.Country;

            player.PlayerUser = user;


            _context.Add(player);


            await _context.SaveChangesAsync();

            return View();
        }

        // GET: Player/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.players == null)
            {
                return NotFound();
            }

            var player = await _context.players.FindAsync(id);
            if (player == null)
            {
                return NotFound();
            }
            return View(player);
        }

        // POST: Player/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlayId,PlayerName,Country,Speciality,Description,BasePrice")] Player player)
        {
            if (id != player.PlayId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(player);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerExists(player.PlayId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(player);
        }

        // GET: Player/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.players == null)
            {
                return NotFound();
            }

            var player = await _context.players
                .FirstOrDefaultAsync(m => m.PlayId == id);
            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        // POST: Player/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.players == null)
            {
                return Problem("Entity set 'PlayerContext.players'  is null.");
            }
            var player = await _context.players.FindAsync(id);
            if (player != null)
            {
                _context.players.Remove(player);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerExists(int id)
        {
          return _context.players.Any(e => e.PlayId == id);
        }
    }
    
}

Player-mgt-system/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.dto;
using Player_mgt_system.Models;

namespace Player_mgt_system.Controllers;

public class ReportController : Controller
{
    private readonly PlayerContext _context;

    public ReportController(PlayerContext context)
    {
        _context = context;
    }
    // GET
    public IActionResult Index()
    {
       

        return View();
    }
    public  IActionResult  getReportData()
    {
        var listTrophy =  _context.Trophy.ToList();
        var listPlayer = _context.players.ToList();
        var listOwner = _context.Owner.ToList();
        var listTeam =  _context.Team.ToList();

        ReportDto reportDto = new ReportDto();
        reportDto.Owners = listOwner;
        reportDto.PlayersList = listPlayer;
        reportDto.Trophies = listTrophy;
        reportDto.Teams = listTeam;
        return Ok(reportDto);
    }
}

Player-mgt-system/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.Models;

namespace Player_mgt_system.Controllers
{
    public class TeamController : Controller
    {
        private readonly PlayerContext _context;

        public TeamController(PlayerContext context)
        {
            _context = context;
        }

        // GET: Team
        public async Task<IActionResult> Index()
        {
            if(!string.IsNullOrWhiteSpace(HttpContext.Session.GetString(SessionVariables.SessionKeyUsername))){
                return _context.Team != null ? 
                    View(await _context.Team.ToListAsync()) :
                    Problem("Entity set 'PlayerContext.Team'  is null.");       
            }

            return RedirectToAction("Index", "Login");
        }

        // GET: Team/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Team/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Team/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamId,TeamName,TeamOwner,TeamState,Description,MaxPrice")] Team team)
        {
                var owner = await _context.Owner
                .FirstOrDefaultAsync(m => m.OwnerId == Int32.Parse(team.TeamOwner));
                team.TeamOwner = owner.OwnerName;
                _context.Add(team);
                await _context.SaveChangesAsync();
                return View();
            
        }

        // GET: Team/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Team/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeamId,TeamName,TeamOwner,TeamState,Description,MaxPrice")] Team team)
        {
            if (id != team.TeamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.TeamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Team/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Team == null)
            {
                return Problem("Entity set 'PlayerContext.Team'  is null.");
            }
            var team = await _context.Team.FindAsync(id);
            if (team != null)
            {
                _context.Team.Remove(team);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
          return (_context.Team?.Any(e => e.TeamId == id)).GetValueOrDefault();
        }
        
        public async Task<IActionResult> AddPlayers(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return null;
        }
        public IActionResult GetTeams()
        {
            var teams =
                _context.Team.Select(r=>r).ToList();

            return Ok(teams);
        }
    }
}

Player-mgt-system/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auction Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/playerMgtStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Player_mgt_system.styles.css" asp-append-version="true" />
    
    </head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Auction MGT</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1" id="menuSection">
                        <li class="nav-item" id="manageTeam">
                            <a class="nav-link text-white" asp-area="" asp-controller="Team" asp-action="Index" >Manage Teams</a>
                        </li>
                        <li class="nav-item" id="managePlayers">
                            <a class="nav-link text-white" asp-area="" asp-controller="Player" asp-action="Index" >Manage Players</a>
                        </li>
                        <li class="nav-item" id="manageTrophy">
                            <a class="nav-link text-white" asp-area="" asp-controller="Trophy" asp-action="Index" >Manage Trophy</a>
                        </li>
                        
                        <li class="nav-item" id="manageAuction">
                            <a class="nav-link text-white" asp-area="" asp-controller="Trophy" asp-action="Index" >Manage Auction</a>
                        </li>
                        <li class="nav-item" id="applyTrophy">
                            <a class="nav-link text-white" asp-area="" asp-controller="Playertrophy" asp-action="Index" >Apply for Trophy</a>
                        </li>
                        <li class="nav-item" id="reports">
                            <a class="nav-link text-white" asp-area="" asp-controller="Report" asp-action="Index" >Reports</a>
                        </li>
                        <li class="nav-item" id="logout" style="margin-left: 512px;cursor: pointer">
                            <a  class="nav-link text-white" ><i class="fa-sharp fa-solid fa-right-from-bracket"></i> Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/81cf753544.js" crossorigin="anonymous"></script>
    <script type="text/javascript">
        window.onload = function() {
            getUserData();
            if (window.location.href==="http://localhost:54565/"||window.location.href==="http://localhost:54565/login"||window.location.href==="http://localhost:54565/login/index"){
                document.getElementById("menuSection").style.display = "none";
            }else{
                document.getElementById("menuSection").style.display = "flex";
            }
          
          
        };
        function getUserData(){
             $.ajax({
                type: 'GET',
                url:  '@Url.Action("GetUserData", "Dashboard")',
                success: function (result) {
                    console.log(result);
                    sessionStorage.setItem("ROLE",result[0].role);
                    sessionStorage.setItem("USERNAME",result[0].username);
                    manageMenue(result[0].role);
                },
                error: function () {
                    console.log('Failed ');
                }
             });
             
             
        }
        function manageMenue(role){
            if (role==="USER_ADMIN"){
               document.getElementById("applyTrophy").style.display = "none";
            }else if (role==="USER_PLAYER"){
                document.getElementById("manageAuction").style.display = "none";
               
                document.getElementById("manageTrophy").style.display = "none";
                document.getElementById("managePlayers").style.display = "none";
                document.getElementById("manageTeam").style.display = "none";
                document.getElementById("reports").style.display = "none";
                       
            }else if (role==="USER_OWNER"){
                document.getElementById("applyTrophy").style.display = "none";
                 document.getElementById("applyTrophy").style.display = "none";
                document.getElementById("manageAuction").style.display = "none";
                document.getElementById("manageTrophy").style.display = "none";
                document.getElementById("manageTeam").style.display = "none";
                 document.getElementById("reports").style.display = "none";
            }
        }
        function logout() {
           $.ajax({
                          type: 'GET',
                          url:  '@Url.Action("", "Login")',
                          success: function (result) {
                              console.log(result);
                              sessionStorage.clear("ROLE");
                              sessionStorage.clear("USERNAME");
                          },
                          error: function () {
                              console.log('Failed ');
                          }
                       });
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>