Player-mgt-system/Models/Team.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Player_mgt_system.Models
{
    public class Team
    {
        [Key]
        public int TeamId { get; set; }
        [Column(TypeName="nvarchar(250)")]
        [DisplayName("Team Name")]
        [Required]
        public string TeamName { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string TeamOwner { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string TeamState { get; set; }
        [Column(TypeName = "nvarchar(250)")]
        public string Description { get; set; }
        public decimal MaxPrice { get; set; }

        public ICollection<Player> Players;
        
        public List<Trophy_Team> Trophy_Team { get; set; }
    }
}

Player-mgt-system/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.Models;

namespace Player_mgt_system.Controllers
{
    public class OwnerController : Controller
    {
        private readonly PlayerContext _context;

        public OwnerController(PlayerContext context)
        {
            _context = context;
        }

        public IActionResult GetOwners()
        {
            var owners =
                _context.Owner.Select(r=>r).ToList();

            return Ok(owners);
        }

       
    }
}

Player-mgt-system/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Player_mgt_system.Models;

namespace Player_mgt_system.Controllers
{
    public class TeamController : Controller
    {
        private readonly PlayerContext _context;

        public TeamController(PlayerContext context)
        {
            _context = context;
        }

        // GET: Team
        public async Task<IActionResult> Index()
        {
            if(!string.IsNullOrWhiteSpace(HttpContext.Session.GetString(SessionVariables.SessionKeyUsername))){
                return _context.Team != null ? 
                    View(await _context.Team.ToListAsync()) :
                    Problem("Entity set 'PlayerContext.Team'  is null.");       
            }

            return RedirectToAction("Index", "Login");
        }

        // GET: Team/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // GET: Team/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Team/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamId,TeamName,TeamOwner,TeamState,Description,MaxPrice")] Team team)
        {
                var owner = await _context.Owner
                .FirstOrDefaultAsync(m => m.OwnerId == Int32.Parse(team.TeamOwner));
                team.TeamOwner = owner.OwnerName;
                _context.Add(team);
                await _context.SaveChangesAsync();
                return View();
            
        }

        // GET: Team/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team.FindAsync(id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Team/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeamId,TeamName,TeamOwner,TeamState,Description,MaxPrice")] Team team)
        {
            if (id != team.TeamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.TeamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Team/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Team == null)
            {
                return Problem("Entity set 'PlayerContext.Team'  is null.");
            }
            var team = await _context.Team.FindAsync(id);
            if (team != null)
            {
                _context.Team.Remove(team);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
          return (_context.Team?.Any(e => e.TeamId == id)).GetValueOrDefault();
        }
        
        public async Task<IActionResult> AddPlayers(int? id)
        {
            if (id == null || _context.Team == null)
            {
                return NotFound();
            }

            var team = await _context.Team
                .FirstOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return null;
        }
        public IActionResult GetTeams()
        {
            var teams =
                _context.Team.Select(r=>r).ToList();

            return Ok(teams);
        }
    }
}

Player-mgt-system/Views/Team/Create.cshtml
@model Player_mgt_system.Models.Team

@{
    ViewData["Title"] = "Create";
}

<div class="card">
  <div class="card-header">
    Create New Team
  </div>
  <div class="card-body">
      
              <form asp-action="Create">
              <div class="row">
                  <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                  <div class="form-group col-md-6">
                      <label asp-for="TeamName" class="control-label"></label>
                      <input asp-for="TeamName" class="form-control" />
                      <span asp-validation-for="TeamName" class="text-danger"></span>
                  </div>
                  <div class="form-group col-md-6">
                      <label asp-for="TeamOwner" class="control-label"></label>
                       <select asp-for="TeamOwner" class="form-select" aria-label="Default select example" id="selectOwner" >
                       </select>
                      <span asp-validation-for="TeamOwner" class="text-danger"></span>
                  </div>
                  <div class="form-group col-md-6">
                      <label asp-for="TeamState" class="control-label"></label>
                      <input asp-for="TeamState" class="form-control" />
                      <span asp-validation-for="TeamState" class="text-danger"></span>
                  </div>
                  <div class="form-group col-md-6">
                      <label asp-for="Description" class="control-label"></label>
                      <input asp-for="Description" class="form-control" />
                      <span asp-validation-for="Description" class="text-danger"></span>
                  </div>
                  <div class="form-group col-md-6">
                      <label asp-for="MaxPrice" class="control-label"></label>
                      <input asp-for="MaxPrice" class="form-control" />
                      <span asp-validation-for="MaxPrice" class="text-danger"></span>
                  </div>
              <div class="form-group col-md-6 mt-2">
                  <input type="submit" value="Create" class="btn btn-success" />
              </div>
               </div>
              </form>
     
  </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    getOwners();
    function getOwners(){
        $.ajax({
           type: 'GET',
           url:  '@Url.Action("GetOwners", "Owner")',
           success: function (result) {
               console.log('owners',result);
               $.each(result, function (key, entry) {
                   $("#selectOwner").append($('<option></option>').
                   attr('value', entry.ownerId).text(entry.ownerName));
                 })
           },
           error: function () {
               console.log('Failed ');
           }
        });       
    }

</script>

Player-mgt-system/Views/Team/Delete.cshtml
@model Player_mgt_system.Models.Team

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamOwner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamOwner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamState)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamState)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-route-id="@Model.TeamId">
        <input type="hidden" asp-for="TeamId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Player-mgt-system/Views/Team/Details.cshtml
@model Player_mgt_system.Models.Team

@{
    ViewData["Title"] = "Details";
}

<div class="card">
    <div class="card-header">
        Team Details
    </div>
    <div class="card-body">
       <div>
           
           <dl class="row">
               <dt class = "col-sm-2">
                   @Html.DisplayNameFor(model => model.TeamName)
               </dt>
               <dd class = "col-sm-10">
                   @Html.DisplayFor(model => model.TeamName)
               </dd>
               <dt class = "col-sm-2">
                   @Html.DisplayNameFor(model => model.TeamOwner)
               </dt>
               <dd class = "col-sm-10">
                   @Html.DisplayFor(model => model.TeamOwner)
               </dd>
               <dt class = "col-sm-2">
                   @Html.DisplayNameFor(model => model.TeamState)
               </dt>
               <dd class = "col-sm-10">
                   @Html.DisplayFor(model => model.TeamState)
               </dd>
               <dt class = "col-sm-2">
                   @Html.DisplayNameFor(model => model.Description)
               </dt>
               <dd class = "col-sm-10">
                   @Html.DisplayFor(model => model.Description)
               </dd>
               <dd class = "col-sm-10">
                   @Html.DisplayFor(model => model.MaxPrice)
               </dd>
           </dl>
       </div>
    </div>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.TeamId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Player-mgt-system/Views/Team/Edit.cshtml
@model Player_mgt_system.Models.Team

@{
    ViewData["Title"] = "Edit";
}
<div class="card">
  <div class="card-header">
    Edit Team Details
  </div>
  <div class="card-body">
    
             <form asp-action="Edit" asp-route-id="@Model.TeamId">
              <div class="row">
                 <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                 <input type="hidden" asp-for="TeamId" />
                 <div class="form-group col-md-6">
                     <label asp-for="TeamName" class="control-label"></label>
                     <input asp-for="TeamName" class="form-control" />
                     <span asp-validation-for="TeamName" class="text-danger"></span>
                 </div>
                 <div class="form-group col-md-6">
                     <label asp-for="TeamOwner" class="control-label"></label>
                     <input asp-for="TeamOwner" class="form-control" />
                     <span asp-validation-for="TeamOwner" class="text-danger"></span>
                 </div>
                 <div class="form-group col-md-6">
                     <label asp-for="TeamState" class="control-label"></label>
                     <input asp-for="TeamState" class="form-control" />
                     <span asp-validation-for="TeamState" class="text-danger"></span>
                 </div>
                 <div class="form-group col-md-6">
                     <label asp-for="Description" class="control-label"></label>
                     <input asp-for="Description" class="form-control" />
                     <span asp-validation-for="Description" class="text-danger"></span>
                 </div>
                 <div class="form-group col-md-6">
                     <label asp-for="MaxPrice" class="control-label"></label>
                     <input asp-for="MaxPrice" class="form-control" />
                     <span asp-validation-for="MaxPrice" class="text-danger"></span>
                 </div>
                 
              <div class="form-group col-md-6 mt-4">
                  <input type="submit" value="Edit" class="btn btn-success" />
              </div>
               </div>
             </form>
    
     
  </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

Player-mgt-system/Views/Team/Index.cshtml
@model IEnumerable<Player_mgt_system.Models.Team>

@{
    ViewData["Title"] = "Index";
}


<p>
    <a asp-action="Create" style="color: green"><i class="fa-solid fa-file-circle-plus"></i> Create New Team</a>
</p>
<div class="card">
  <div class="card-header">
    Team Details
  </div>
    <div class="card-body">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.TeamName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TeamOwner)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TeamState)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.MaxPrice)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TeamName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TeamOwner)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TeamState)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaxPrice)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.TeamId" style="color: green"> <i class="fa-regular fa-pen-to-square"></i> Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.TeamId"><i class="fa-regular fa-eye"></i> View</a> |
                        <a asp-action="Delete" asp-route-id="@item.TeamId" style="color: red"><i class="fa-regular fa-trash"></i> Delete</a>
                        
                    </td>
                </tr>
        }
            </tbody>
        </table>
    </div>
</div>